$(function(){
	clickImg();
});
function clickImg(){
	$("#baoliyun").click(function(){
		//默认
		$("#backgroundC").css("background-color","#EA5504")
	});
	$("#zulin").click(function(){
		$("#backgroundC").css("background-color","#438dc9")
	});
	$("#ziguan").click(function(){
		$("#backgroundC").css("background-color","#57d492")
	});
	$("#yunpiao").click(function(){
		$("#backgroundC").css("background-color","#18cfd6")
	});
	$("#jiaoyi").click(function(){
		$("#backgroundC").css("background-color","#e85b09")
	});
}
